### ISSUE TITLE
Question about energy conservation in mass spring

### ISSUE THREAD

**Issue by Yihao-Shi** [liminchen/solid-sim-tutorial#2]
The energy consumption in the mass spring simulation is noticeable when damping terms are not added into the energy function. Besides, using different time steps, such as 0.004 and 0.0004, yields significantly different results. So I am curious about the underlying reasons.

**Comment by liminchen** [comment]
This is because implicit Euler time integration is used, which is only 1st order and it damps out energy very quickly. We use it for it's L-stability.

**Comment by Yihao-Shi** [comment]
thanks
